### ISSUE TITLE
Small Typo in Example

### ISSUE THREAD

**Issue by harrellbm** [tomeichlersmith/zen-zine#1]
Hi just wanted to point out a small typo in the example file. The commented out `page_boarder` argument is expected by the function without an s but the example has `page_boarders`

Obviously not a big deal but may throw some people for a loop!

**Comment by tomeichlersmith** [comment]
Thank you! I've updated the example in the README here :) I don't plan to update the version in [typst universe](https://typst.app/universe/package/zen-zine) but I'll see if they'll let me update the README there as well

**Comment by harrellbm** [comment]
@tomeichlersmith I also have to say thanks for this package! I have enjoyed using it. It also inspired me to make a similar package called bookletic for booklet setting.
